### ISSUE TITLE
Insert all stock data into cassandra

### ISSUE THREAD

**Issue by Ramblurr** [Ramblurr/CapstonePython#10]
The insert process becomes very slow after a couple minutes. What is the bottle neck?

We have yet to get data after the Bs inserted!

**Comment by Ramblurr** [comment]
So after a couple hours of research and testing, David and I determined the issue is Java/cassandra related, as opposed to us hitting CPU, RAM, disk or network IO bottlenecks.

The following two links have information regarding this issue:
- http://wiki.apache.org/cassandra/FAQ#slows_down_after_lotso_inserts
- http://wiki.apache.org/cassandra/MemtableThresholds

David tweaked these values and saw a modest increase in insertion speed, however it still took 10+ minutes to insert 250,000 records... this is only 25% of the A file... so we have some serious tweaking still to do.

The values we tweaked were in the CLI as follows:

```
update column family Stocks with memtable_operations=0.001;
update column family Stocks with memtable_throughput=5;
```

The first one causes cassandra to flush writes to disk after 1000 operations, and the second causes it to flush after 5megabytes.

**Comment by Ramblurr** [comment]
Using some fancy math we figured out were are getting around 200 inserts/sec per core. According to some bro in IRC we should be getting 2000-4000 inserts/sec per core.

**Comment by Ramblurr** [comment]
Just for kicks we tried inserting from the node itself (instead of the micro instance) and KABOOM instant improvement to 10k+ records/sec.

Obviously our micro instance couldn't handle the load of inserting. **Why not**?

**Comment by dmazary** [comment]
Also note that when we inserted from the node itself, Cassandra gave the best performance at its default settings. It would be interesting to insert from a large (or small) instance that isn't running Cassandra, to measure what the bottleneck is.

The [EC2 instance type page](http://aws.amazon.com/ec2/instance-types/) has an interesting description of the instance types. The micro instance doesn't even guarantee a single compute unit like the small does, but instead can burst up to 2 compute units.

**Comment by Ramblurr** [comment]
Hm interesting. As we discussed after leaving the lab, it seems that the bottleneck on the micro was definitely the CPU.

The behavior we saw where it would run well for a bit, then totally stop for awhile seems consistent with their being a lack of CPU Compute Units. Our insert process simply wasn't being scheduled enough on the CPU.

**Comment by Ramblurr** [comment]
Figured it out.
