### ISSUE TITLE
Understand HBase

### ISSUE THREAD

**Issue by dmazary** [Ramblurr/CapstonePython#13]

**Comment by dmazary** [comment]
http://hbase.apache.org/book.html
Also read BigTable if you haven't yet.

**Comment by dmazary** [comment]
Read this too: http://whynosql.com/cassandra-vs-hbase/
and this: http://www.slideshare.net/hmisty/20090713-hbase-schema-design-case-studies
and then you will know.

**Comment by astreet** [comment]
http://wiki.apache.org/hadoop/Hbase/DataModel
