### ISSUE TITLE
Find Val

### ISSUE THREAD

**Issue by dmazary** [Ramblurr/CapstonePython#20]
Where is he?

**Comment by niothiel** [comment]
Val's still been around, just been buttraped with work. If you guys want to
assign me some tasks, as well as giving me an ssh key so I actually have
access to the cluster, that would be awesome. I will work on as much as i
can, and I will take on whatever you throw in my direction. Sorry you
haven't heard very much from me, this semester has been hell on wheels for
me, and i feel bad that you guys had to pick up my slack for my
shortcomings.

Don't wait, assign me some issues!

On Tue, Apr 12, 2011 at 4:04 PM, dmazary <
reply@reply.github.com>wrote:

> Where is he?
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/Ramblurr/CapstonePython/issues/20

## 

-Val Komarov

**Comment by astreet** [comment]
You need to come to our meetings and assign yourself issues based on what the rest of the group is doing.  First, you probably need to talk to Butt since he seemed concerned that he hasn't seen you at any of our T/R meetings since the beginning of the semester.

**Comment by niothiel** [comment]
When's our next meeting?
On Apr 14, 2011 2:06 PM, "astreet" <
reply@reply.github.com>
wrote:

**Comment by dmazary** [comment]
As we've been saying in our emails, we've been [meeting](http://happy.cs.vt.edu/~manuel/courses/class/cs4244-S11) during class time in McBryde 124. Meetings with Dr. Butt on Tuesdays and group meetings on Thursdays.

So the next meeting after the one we're in right now is on Tuesday.
