### ISSUE TITLE
Ticker symbol autocomplete

### ISSUE THREAD

**Issue by dmazary** [Ramblurr/CapstonePython#4]
The web page should suggest ticker symbols when typing in the text box.

**Comment by Ramblurr** [comment]
This should be easy to do with jquery (we are already using jquery for the datepicker)

some urls to get started:
- http://docs.jquery.com/UI/Autocomplete
- http://choosedaily.com/1308/15-jquery-autocomplete-plugins-tutorials/
- http://www.devbridge.com/projects/autocomplete/jquery/
