### ISSUE TITLE
Choose an HBase python api to use

### ISSUE THREAD

**Issue by dmazary** [Ramblurr/CapstonePython#6]
https://encrypted.google.com/search?q=hbase+python

**Comment by Ramblurr** [comment]
Here is a helpful blog post about hbase and python

http://yannramin.com/2008/07/19/using-facebook-thrift-with-python-and-hbase/

**Comment by Ramblurr** [comment]
Maybe this too?
- https://github.com/hammer/pyhbase
- http://whynosql.com/using-thrift-python-client-with-hbase/

**Comment by dmazary** [comment]
[pybase](https://github.com/antoniobarbuzzi/pybase) is based on pycassa. I'm looking at that now.

**Comment by Ramblurr** [comment]
pybase it is
