### ISSUE TITLE
Install HBase on some EC2 instances

### ISSUE THREAD

**Issue by Ramblurr** [Ramblurr/CapstonePython#7]
We need a ready to deploy HBase AMI for EC2.

**Comment by dmazary** [comment]
http://wiki.apache.org/hadoop/HBasePackages

**Comment by dmazary** [comment]
This is more involved than Cassandra; it needs HBase, Hadoop, and Zookeeper. I'm working on this using the hbase-ec2 deployment scripts which deploy premade hbase EC2 AMIs with everything already set up.

**Comment by dmazary** [comment]
Done. Wrote up on Google Doc.
