### ISSUE TITLE
Choose a memcachedb api to use

### ISSUE THREAD

**Issue by dmazary** [Ramblurr/CapstonePython#8]
Twisted has a memcached interface.

**Comment by Ramblurr** [comment]
A good intro to memcachedb:
- http://www.scribd.com/doc/9191169/Memcachedb-Guide-10

Regarding python and memcachedb:
- http://stackoverflow.com/questions/868690/good-examples-of-python-memcache-memcached-being-used-in-python
- http://stackoverflow.com/questions/2524881/which-python-module-to-use-for-memcached

Actual libraries:
- http://www.tummy.com/Community/software/python-memcached/
- http://code.google.com/p/python-libmemcached/
